### ISSUE TITLE
 Bimangle.ForgeEngine.Dgn load

### ISSUE THREAD

**Issue by otofoto** [bimangle/forge-engine-samples#6]
Unable to load Bimangle.ForgeEngine.Dgn in Microstation CE

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Bentley.Internal.MstnPlatformNET.DotNetShim.Launcher.GetAddInTypeThroughReflection(Int32* statusCodeP, String* taskIDOverridePP, String assemblyRootName, String taskId)
   at Bentley.Internal.MstnPlatformNET.DotNetShim.Launcher.LoadMdlProgram(IntPtr statusCodeP, String mdlAppNameParam, String taskID, IntPtr forkFunc, IntPtr forkParams)

**Comment by bimangle** [comment]
Looks like a plug-in deployment problem.

If the plug-in is compiled in Debug mode, the plug-in is automatically deployed.
